Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Projet.DAL;
using Projet.Models;

namespace Projet.Controllers
{
    public class AdminsController : Controller
    {
        private F1Context db = new F1Context();

        public ActionResult Index()
        {
            if (Session["AdminID"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        public ActionResult Login()
        {
            ViewBag.error = TempData["erreur"];

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string pseudo, string mdp)
        {
            if (ModelState.IsValid)
            {

                var f_password = GetMD5(mdp);
                var data = db.Admins.Where(s => s.pseudo.Equals(pseudo) && s.mdp.Equals(f_password)).FirstOrDefault();
                if (data != null)
                {

                    Session["pseudo"] = data.pseudo;
                    Session["AdminID"] = data.AdminID;


                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    TempData["erreur"] = "Erreur, login ou mot de passe incorect";

                    return RedirectToAction("Login");
                }
            }
            return View("Login");
        }

        public ActionResult Logout()
        {
            Session.Clear();//remove session
            return RedirectToAction("Login");
        }


        public static string GetMD5(string str)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            byte[] fromData = Encoding.UTF8.GetBytes(str);
            byte[] targetData = md5.ComputeHash(fromData);
            string byte2String = null;

            for (int i = 0; i < targetData.Length; i++)
            {
                byte2String += targetData[i].ToString("x2");

            }
            return byte2String;
        }

    }
}

Controllers/CircuitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projet.DAL;
using Projet.Models;

namespace Projet.Controllers
{
    public class CircuitsController : Controller
    {
        private F1Context db = new F1Context();

        // GET: Circuits
        public ViewResult Index(string searchString)
        {
            ViewBag.CurrentFilter = searchString;
            var circuits = from c in db.Circuits
                          select c;
            if (!String.IsNullOrEmpty(searchString))
            {
                circuits = circuits.Where(p => p.Pays.Contains(searchString));
            }
            return View(circuits.ToList());
        }

        // GET: Circuits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Circuit circuit = db.Circuits.Find(id);
            if (circuit == null)
            {
                return HttpNotFound();
            }
            return View(circuit);
        }

        // GET: Circuits/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Circuits/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CircuitID,Nom_c,Ville,Pays")] Circuit circuit)
        {
            if (ModelState.IsValid)
            {
                db.Circuits.Add(circuit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(circuit);
        }

        // GET: Circuits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Circuit circuit = db.Circuits.Find(id);
            if (circuit == null)
            {
                return HttpNotFound();
            }
            return View(circuit);
        }

        // POST: Circuits/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CircuitID,Nom_c,Ville,Pays")] Circuit circuit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(circuit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(circuit);
        }

        // GET: Circuits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Circuit circuit = db.Circuits.Find(id);
            if (circuit == null)
            {
                return HttpNotFound();
            }
            return View(circuit);
        }

        // POST: Circuits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Circuit circuit = db.Circuits.Find(id);
            db.Circuits.Remove(circuit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/EcuriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projet.DAL;
using Projet.Models;

namespace Projet.Controllers
{
    public class EcuriesController : Controller
    {
        private F1Context db = new F1Context();

        // GET: Ecuries
        public ViewResult Index(string searchString)
        {
            ViewBag.CurrentFilter = searchString;
            var ecuries = from e in db.Ecuries
                           select e;
            if (!String.IsNullOrEmpty(searchString))
            {
                ecuries = ecuries.Where(e => e.Nom_e.Contains(searchString));
            }
            return View(ecuries.ToList());
        }

        // GET: Ecuries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ecurie ecurie = db.Ecuries.Find(id);
            if (ecurie == null)
            {
                return HttpNotFound();
            }
            return View(ecurie);
        }

        // GET: Ecuries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ecuries/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EcurieID,Nom_e,Nationalite_e")] Ecurie ecurie)
        {
            if (ModelState.IsValid)
            {
                db.Ecuries.Add(ecurie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ecurie);
        }

        // GET: Ecuries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ecurie ecurie = db.Ecuries.Find(id);
            if (ecurie == null)
            {
                return HttpNotFound();
            }
            return View(ecurie);
        }

        // POST: Ecuries/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EcurieID,Nom_e,Nationalite_e")] Ecurie ecurie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ecurie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ecurie);
        }

        // GET: Ecuries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ecurie ecurie = db.Ecuries.Find(id);
            if (ecurie == null)
            {
                return HttpNotFound();
            }
            return View(ecurie);
        }

        // POST: Ecuries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ecurie ecurie = db.Ecuries.Find(id);
            db.Ecuries.Remove(ecurie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/PilotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projet.DAL;
using Projet.Models;

namespace Projet.Controllers
{
    public class PilotesController : Controller
    {
        private F1Context db = new F1Context();

        // GET: Pilotes
        public ViewResult Index(string searchString)
        {
            ViewBag.CurrentFilter = searchString;
            var pilotes = from p in db.Pilotes
                         select p;
            if (!String.IsNullOrEmpty(searchString))
            {
                pilotes = pilotes.Where(p => p.Nom.Contains(searchString));
            }
            return View(pilotes.ToList());
        }

        // GET: Pilotes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pilote pilote = db.Pilotes.Find(id);
            if (pilote == null)
            {
                return HttpNotFound();
            }
            return View(pilote);
        }

        // GET: Pilotes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pilotes/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PiloteID,Numero,Nom,Prenom,Date_Naissance")] Pilote pilote)
        {
            if (ModelState.IsValid)
            {
                db.Pilotes.Add(pilote);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pilote);
        }

        // GET: Pilotes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pilote pilote = db.Pilotes.Find(id);
            if (pilote == null)
            {
                return HttpNotFound();
            }
            return View(pilote);
        }

        // POST: Pilotes/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PiloteID,Numero,Nom,Prenom,Date_Naissance")] Pilote pilote)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pilote).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pilote);
        }

        // GET: Pilotes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pilote pilote = db.Pilotes.Find(id);
            if (pilote == null)
            {
                return HttpNotFound();
            }
            return View(pilote);
        }

        // POST: Pilotes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pilote pilote = db.Pilotes.Find(id);
            db.Pilotes.Remove(pilote);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jQuery and JS bundle w/ Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <title>@ViewBag.Title - Formula 1</title>
</head>
@RenderSection("Styles", false)
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Formula 1</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href=" @Url.Action("Index","Home")">Accueil <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=" @Url.Action("Index","Pilotes") "> Pilotes </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=" @Url.Action("Index","Ecuries")">Ecuries</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=" @Url.Action("Index","Circuits")">Circuits</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Resultats
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href=" @Url.Action("Index","Resultats",new{id = 3})">Autriche</a>
                        <a class="dropdown-item" href=" @Url.Action("Index","Resultats",new{id = 6})">Hongrie</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=" @Url.Action("Login","Admins")">Connexion</a>
                </li>
                @if (Session["pseudo"] != null)
                {
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Logout","Admins")">Deconnexion</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=" @Url.Action("Create","Pilotes") "> Ajouter un pilote </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=" @Url.Action("Create","Ecuries")">Ajouter une ecurie</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=" @Url.Action("Create","Circuits")">Ajouter un circuit</a>
                    </li>
                }
            </ul>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="float-end"><a href="#">Back to top</a></p>
            <p>&copy; 2020 Formula 1 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
        </footer>
    </div>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</body>
</html>
@RenderSection("scripts", required: false)